package HW_01_Gradle;

import org.apache.commons.lang3.builder.EqualsBuilder;

import java.util.Random;
import java.util.stream.Stream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private final static Random RAND = new Random();

    public static void main(String[] args) {
        Root firstRoot = new Root();
        firstRoot.setName("firstRoot");
        fillRootList(firstRoot, 5);
        System.out.println(firstRoot);
        System.out.println();

        //Создаем класс GsonParser
        GsonParser parser = new GsonParser();
        //тест записи
        parser.writeToJson(firstRoot);
        //Создаем класс Root и считываем в него из файла json
        Root root = parser.parse();
        System.out.println("Gson:");
        System.out.println(root);

        System.out.println();
        System.out.println("Commons lang:");
        People people1 = new People("Tom", 35);
        People people2 = new People("Garry", 21);
        People people3 = new People("Garry", 21);

        System.out.println("People1 and people2 is Equals: " + EqualsBuilder.reflectionEquals(people1, people2, true));
        System.out.println("People1 and people2 is Equals: " + EqualsBuilder.reflectionEquals(people3, people2, true));
    }
    private static People getNewPeople() {
        String[] names = {"Garry", "Germiona", "Ron", "Severus", "Dambldor", "Tom", "Sirius", "Lupin", "jinny"};
        return new People(names[RAND.nextInt(8)],RAND.nextInt(14, 50));
    }
    private static void fillRootList(Root root, int size){
        for (int i = 0; i < size; i++) {
            root.getPeople().add(getNewPeople());
        }
    }
}
